language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed manalrashwan/udagram-api-feed:v1a
  - docker tag udagram-api-user manalrashwan/udagram-api-user:v1a
  - docker tag udagram-frontend manalrashwan/udagram-frontend:v1a
  - docker tag udagram-reverseproxy manalrashwan/udagram-reverseproxy:v1a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push manalrashwan/udagram-api-feed:v1a
  - docker push manalrashwan/udagram-api-user:v1a
  - docker push manalrashwan/udagram-frontend:v1a
  - docker push manalrashwan/udagram-reverseproxy:v1a
